# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright (C) 2023 igo95862
---

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

sphinx:
  configuration: "docs/conf.py"

python:
  install:
    - requirements: docs/requirements.txt
