# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class AdslSettings(NetworkManagerSettingsMixin):
    """ADSL Settings"""

    encapsulation: Optional[str] = field(
        metadata={'dbus_name': 'encapsulation', 'dbus_type': 's'},
        default=None,
    )
    password: Optional[str] = field(
        metadata={'dbus_name': 'password', 'dbus_type': 's'},
        default=None,
    )
    password_flags: Optional[int] = field(
        metadata={'dbus_name': 'password-flags', 'dbus_type': 'i'},
        default=None,
    )
    protocol: Optional[str] = field(
        metadata={'dbus_name': 'protocol', 'dbus_type': 's'},
        default=None,
    )
    username: Optional[str] = field(
        metadata={'dbus_name': 'username', 'dbus_type': 's'},
        default=None,
    )
    vci: Optional[int] = field(
        metadata={'dbus_name': 'vci', 'dbus_type': 'u'},
        default=None,
    )
    vpi: Optional[int] = field(
        metadata={'dbus_name': 'vpi', 'dbus_type': 'u'},
        default=None,
    )
