# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses-jinja.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class BluetoothSettings(NetworkManagerSettingsMixin):
    """Bluetooth Settings"""

    bdaddr: Optional[bytes] = field(
        metadata={
            'dbus_name': 'bdaddr',
            'dbus_type': 'ay',
        },
        default=None,
    )
    """The Bluetooth address of the device."""
    bluetooth_type: Optional[str] = field(
        metadata={
            'dbus_name': 'type',
            'dbus_type': 's',
        },
        default=None,
    )
    """Either "dun" for Dial-Up Networking connections or "panu" for Personal
    Area Networking connections to devices supporting the NAP profile."""
