# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class BondPortSettings(NetworkManagerSettingsMixin):
    """Bond Port Settings"""

    queue_id: Optional[int] = field(
        metadata={'dbus_name': 'queue-id', 'dbus_type': 'u'},
        default=None,
    )
