# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Optional
from .base import NetworkManagerSettingsMixin
from .datatypes import Vlans


@dataclass
class BridgePortSettings(NetworkManagerSettingsMixin):
    """Bridge Port Settings"""

    hairpin_mode: Optional[bool] = field(
        metadata={'dbus_name': 'hairpin-mode', 'dbus_type': 'b'},
        default=False,
    )
    """Enables or disables "hairpin mode" for the port, which allows frames to be
    sent back out through the port the frame was received on."""
    path_cost: Optional[int] = field(
        metadata={'dbus_name': 'path-cost', 'dbus_type': 'u'},
        default=100,
    )
    """The Spanning Tree Protocol (STP) port cost for destinations via this
    port."""
    priority: Optional[int] = field(
        metadata={'dbus_name': 'priority', 'dbus_type': 'u'},
        default=32,
    )
    vlans: Optional[List[Vlans]] = field(
        metadata={'dbus_name': 'vlans',
                  'dbus_type': 'aa{sv}',
                  'dbus_inner_class': Vlans},
        default=None,
    )
