# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Optional
from .base import NetworkManagerSettingsMixin
from .datatypes import Vlans


@dataclass
class BridgeSettings(NetworkManagerSettingsMixin):
    """Bridging Settings"""

    ageing_time: Optional[int] = field(
        metadata={'dbus_name': 'ageing-time', 'dbus_type': 'u'},
        default=300,
    )
    forward_delay: Optional[int] = field(
        metadata={'dbus_name': 'forward-delay', 'dbus_type': 'u'},
        default=15,
    )
    group_address: Optional[bytes] = field(
        metadata={'dbus_name': 'group-address', 'dbus_type': 'ay'},
        default=None,
    )
    group_forward_mask: Optional[int] = field(
        metadata={'dbus_name': 'group-forward-mask', 'dbus_type': 'u'},
        default=None,
    )
    hello_time: Optional[int] = field(
        metadata={'dbus_name': 'hello-time', 'dbus_type': 'u'},
        default=2,
    )
    interface_name: Optional[str] = field(
        metadata={'dbus_name': 'interface-name', 'dbus_type': 's'},
        default=None,
    )
    mac_address: Optional[bytes] = field(
        metadata={'dbus_name': 'mac-address', 'dbus_type': 'ay'},
        default=None,
    )
    max_age: Optional[int] = field(
        metadata={'dbus_name': 'max-age', 'dbus_type': 'u'},
        default=20,
    )
    multicast_hash_max: Optional[int] = field(
        metadata={'dbus_name': 'multicast-hash-max', 'dbus_type': 'u'},
        default=4096,
    )
    multicast_last_member_count: Optional[int] = field(
        metadata={'dbus_name': 'multicast-last-member-count', 'dbus_type': 'u'},
        default=2,
    )
    multicast_last_member_interval: Optional[int] = field(
        metadata={'dbus_name': 'multicast-last-member-interval',
                  'dbus_type': 't'},
        default=100,
    )
    multicast_membership_interval: Optional[int] = field(
        metadata={'dbus_name': 'multicast-membership-interval',
                  'dbus_type': 't'},
        default=26000,
    )
    multicast_querier: Optional[bool] = field(
        metadata={'dbus_name': 'multicast-querier', 'dbus_type': 'b'},
        default=False,
    )
    multicast_querier_interval: Optional[int] = field(
        metadata={'dbus_name': 'multicast-querier-interval', 'dbus_type': 't'},
        default=25500,
    )
    multicast_query_interval: Optional[int] = field(
        metadata={'dbus_name': 'multicast-query-interval', 'dbus_type': 't'},
        default=12500,
    )
    multicast_query_response_interval: Optional[int] = field(
        metadata={'dbus_name': 'multicast-query-response-interval',
                  'dbus_type': 't'},
        default=1000,
    )
    multicast_query_use_ifaddr: Optional[bool] = field(
        metadata={'dbus_name': 'multicast-query-use-ifaddr', 'dbus_type': 'b'},
        default=False,
    )
    multicast_router: Optional[str] = field(
        metadata={'dbus_name': 'multicast-router', 'dbus_type': 's'},
        default=None,
    )
    multicast_snooping: Optional[bool] = field(
        metadata={'dbus_name': 'multicast-snooping', 'dbus_type': 'b'},
        default=True,
    )
    multicast_startup_query_count: Optional[int] = field(
        metadata={'dbus_name': 'multicast-startup-query-count',
                  'dbus_type': 'u'},
        default=2,
    )
    multicast_startup_query_interval: Optional[int] = field(
        metadata={'dbus_name': 'multicast-startup-query-interval',
                  'dbus_type': 't'},
        default=3125,
    )
    priority: Optional[int] = field(
        metadata={'dbus_name': 'priority', 'dbus_type': 'u'},
        default=32768,
    )
    stp: Optional[bool] = field(
        metadata={'dbus_name': 'stp', 'dbus_type': 'b'},
        default=True,
    )
    vlan_default_pvid: Optional[int] = field(
        metadata={'dbus_name': 'vlan-default-pvid', 'dbus_type': 'u'},
        default=1,
    )
    vlan_filtering: Optional[bool] = field(
        metadata={'dbus_name': 'vlan-filtering', 'dbus_type': 'b'},
        default=False,
    )
    vlan_protocol: Optional[str] = field(
        metadata={'dbus_name': 'vlan-protocol', 'dbus_type': 's'},
        default=None,
    )
    vlan_stats_enabled: Optional[bool] = field(
        metadata={'dbus_name': 'vlan-stats-enabled', 'dbus_type': 'b'},
        default=False,
    )
    vlans: Optional[List[Vlans]] = field(
        metadata={'dbus_name': 'vlans',
                  'dbus_type': 'aa{sv}',
                  'dbus_inner_class': Vlans},
        default=None,
    )
