# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class CdmaSettings(NetworkManagerSettingsMixin):
    """CDMA-based Mobile Broadband Settings"""

    mtu: Optional[int] = field(
        metadata={'dbus_name': 'mtu', 'dbus_type': 'u'},
        default=None,
    )
    number: Optional[str] = field(
        metadata={'dbus_name': 'number', 'dbus_type': 's'},
        default=None,
    )
    password: Optional[str] = field(
        metadata={'dbus_name': 'password', 'dbus_type': 's'},
        default=None,
    )
    password_flags: Optional[int] = field(
        metadata={'dbus_name': 'password-flags', 'dbus_type': 'i'},
        default=None,
    )
    username: Optional[str] = field(
        metadata={'dbus_name': 'username', 'dbus_type': 's'},
        default=None,
    )
