# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class DcbSettings(NetworkManagerSettingsMixin):
    """Data Center Bridging Settings"""

    app_fcoe_flags: Optional[int] = field(
        metadata={'dbus_name': 'app-fcoe-flags', 'dbus_type': 'i'},
        default=None,
    )
    app_fcoe_mode: Optional[str] = field(
        metadata={'dbus_name': 'app-fcoe-mode', 'dbus_type': 's'},
        default=None,
    )
    app_fcoe_priority: Optional[int] = field(
        metadata={'dbus_name': 'app-fcoe-priority', 'dbus_type': 'i'},
        default=None,
    )
    app_fip_flags: Optional[int] = field(
        metadata={'dbus_name': 'app-fip-flags', 'dbus_type': 'i'},
        default=None,
    )
    app_fip_priority: Optional[int] = field(
        metadata={'dbus_name': 'app-fip-priority', 'dbus_type': 'i'},
        default=None,
    )
    app_iscsi_flags: Optional[int] = field(
        metadata={'dbus_name': 'app-iscsi-flags', 'dbus_type': 'i'},
        default=None,
    )
    app_iscsi_priority: Optional[int] = field(
        metadata={'dbus_name': 'app-iscsi-priority', 'dbus_type': 'i'},
        default=None,
    )
    priority_bandwidth: Optional[List[int]] = field(
        metadata={'dbus_name': 'priority-bandwidth', 'dbus_type': 'au'},
        default=None,
    )
    priority_flow_control: Optional[List[int]] = field(
        metadata={'dbus_name': 'priority-flow-control', 'dbus_type': 'au'},
        default=None,
    )
    priority_flow_control_flags: Optional[int] = field(
        metadata={'dbus_name': 'priority-flow-control-flags', 'dbus_type': 'i'},
        default=None,
    )
    priority_group_bandwidth: Optional[List[int]] = field(
        metadata={'dbus_name': 'priority-group-bandwidth', 'dbus_type': 'au'},
        default=None,
    )
    priority_group_flags: Optional[int] = field(
        metadata={'dbus_name': 'priority-group-flags', 'dbus_type': 'i'},
        default=None,
    )
    priority_group_id: Optional[List[int]] = field(
        metadata={'dbus_name': 'priority-group-id', 'dbus_type': 'au'},
        default=None,
    )
    priority_strict_bandwidth: Optional[List[int]] = field(
        metadata={'dbus_name': 'priority-strict-bandwidth', 'dbus_type': 'au'},
        default=None,
    )
    priority_traffic_class: Optional[List[int]] = field(
        metadata={'dbus_name': 'priority-traffic-class', 'dbus_type': 'au'},
        default=None,
    )
