# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List, Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class EthernetSettings(NetworkManagerSettingsMixin):
    """Wired Ethernet Settings"""

    accept_all_mac_addresses: Optional[int] = field(
        metadata={'dbus_name': 'accept-all-mac-addresses', 'dbus_type': 'i'},
        default=None,
    )
    assigned_mac_address: Optional[str] = field(
        metadata={'dbus_name': 'assigned-mac-address', 'dbus_type': 's'},
        default=None,
    )
    auto_negotiate: Optional[bool] = field(
        metadata={'dbus_name': 'auto-negotiate', 'dbus_type': 'b'},
        default=False,
    )
    cloned_mac_address: Optional[bytes] = field(
        metadata={'dbus_name': 'cloned-mac-address', 'dbus_type': 'ay'},
        default=None,
    )
    duplex: Optional[str] = field(
        metadata={'dbus_name': 'duplex', 'dbus_type': 's'},
        default=None,
    )
    generate_mac_address_mask: Optional[str] = field(
        metadata={'dbus_name': 'generate-mac-address-mask', 'dbus_type': 's'},
        default=None,
    )
    mac_address: Optional[bytes] = field(
        metadata={'dbus_name': 'mac-address', 'dbus_type': 'ay'},
        default=None,
    )
    mac_address_blacklist: Optional[List[str]] = field(
        metadata={'dbus_name': 'mac-address-blacklist', 'dbus_type': 'as'},
        default=None,
    )
    mtu: Optional[int] = field(
        metadata={'dbus_name': 'mtu', 'dbus_type': 'u'},
        default=None,
    )
    port: Optional[str] = field(
        metadata={'dbus_name': 'port', 'dbus_type': 's'},
        default=None,
    )
    s390_nettype: Optional[str] = field(
        metadata={'dbus_name': 's390-nettype', 'dbus_type': 's'},
        default=None,
    )
    s390_options: Optional[Dict[str, str]] = field(
        metadata={'dbus_name': 's390-options', 'dbus_type': 'a{ss}'},
        default=None,
    )
    s390_subchannels: Optional[List[str]] = field(
        metadata={'dbus_name': 's390-subchannels', 'dbus_type': 'as'},
        default=None,
    )
    speed: Optional[int] = field(
        metadata={'dbus_name': 'speed', 'dbus_type': 'u'},
        default=None,
    )
    wake_on_lan: Optional[int] = field(
        metadata={'dbus_name': 'wake-on-lan', 'dbus_type': 'u'},
        default=1,
    )
    wake_on_lan_password: Optional[str] = field(
        metadata={'dbus_name': 'wake-on-lan-password', 'dbus_type': 's'},
        default=None,
    )
