# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class HostnameSettings(NetworkManagerSettingsMixin):
    """Hostname settings"""

    from_dhcp: Optional[int] = field(
        metadata={'dbus_name': 'from-dhcp', 'dbus_type': 'i'},
        default=None,
    )
    from_dns_lookup: Optional[int] = field(
        metadata={'dbus_name': 'from-dns-lookup', 'dbus_type': 'i'},
        default=None,
    )
    only_from_default: Optional[int] = field(
        metadata={'dbus_name': 'only-from-default', 'dbus_type': 'i'},
        default=None,
    )
    priority: Optional[int] = field(
        metadata={'dbus_name': 'priority', 'dbus_type': 'i'},
        default=None,
    )
