# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class InfinibandSettings(NetworkManagerSettingsMixin):
    """Infiniband Settings"""

    mac_address: Optional[bytes] = field(
        metadata={'dbus_name': 'mac-address', 'dbus_type': 'ay'},
        default=None,
    )
    mtu: Optional[int] = field(
        metadata={'dbus_name': 'mtu', 'dbus_type': 'u'},
        default=None,
    )
    p_key: Optional[int] = field(
        metadata={'dbus_name': 'p-key', 'dbus_type': 'i'},
        default=None,
    )
    parent: Optional[str] = field(
        metadata={'dbus_name': 'parent', 'dbus_type': 's'},
        default=None,
    )
    transport_mode: Optional[str] = field(
        metadata={'dbus_name': 'transport-mode', 'dbus_type': 's'},
        default=None,
    )
