# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class IpTunnelSettings(NetworkManagerSettingsMixin):
    """IP Tunneling Settings"""

    encapsulation_limit: Optional[int] = field(
        metadata={'dbus_name': 'encapsulation-limit', 'dbus_type': 'u'},
        default=None,
    )
    flags: Optional[int] = field(
        metadata={'dbus_name': 'flags', 'dbus_type': 'u'},
        default=None,
    )
    flow_label: Optional[int] = field(
        metadata={'dbus_name': 'flow-label', 'dbus_type': 'u'},
        default=None,
    )
    input_key: Optional[str] = field(
        metadata={'dbus_name': 'input-key', 'dbus_type': 's'},
        default=None,
    )
    local: Optional[str] = field(
        metadata={'dbus_name': 'local', 'dbus_type': 's'},
        default=None,
    )
    mode: Optional[int] = field(
        metadata={'dbus_name': 'mode', 'dbus_type': 'u'},
        default=None,
    )
    mtu: Optional[int] = field(
        metadata={'dbus_name': 'mtu', 'dbus_type': 'u'},
        default=None,
    )
    output_key: Optional[str] = field(
        metadata={'dbus_name': 'output-key', 'dbus_type': 's'},
        default=None,
    )
    parent: Optional[str] = field(
        metadata={'dbus_name': 'parent', 'dbus_type': 's'},
        default=None,
    )
    path_mtu_discovery: Optional[bool] = field(
        metadata={'dbus_name': 'path-mtu-discovery', 'dbus_type': 'b'},
        default=True,
    )
    remote: Optional[str] = field(
        metadata={'dbus_name': 'remote', 'dbus_type': 's'},
        default=None,
    )
    tos: Optional[int] = field(
        metadata={'dbus_name': 'tos', 'dbus_type': 'u'},
        default=None,
    )
    ttl: Optional[int] = field(
        metadata={'dbus_name': 'ttl', 'dbus_type': 'u'},
        default=None,
    )
