# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class MatchSettings(NetworkManagerSettingsMixin):
    """Match settings"""

    driver: Optional[List[str]] = field(
        metadata={'dbus_name': 'driver', 'dbus_type': 'as'},
        default=None,
    )
    interface_name: Optional[List[str]] = field(
        metadata={'dbus_name': 'interface-name', 'dbus_type': 'as'},
        default=None,
    )
    kernel_command_line: Optional[List[str]] = field(
        metadata={'dbus_name': 'kernel-command-line', 'dbus_type': 'as'},
        default=None,
    )
    path: Optional[List[str]] = field(
        metadata={'dbus_name': 'path', 'dbus_type': 'as'},
        default=None,
    )
