# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses-jinja.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class OvsPatchSettings(NetworkManagerSettingsMixin):
    """OvsPatch Link Settings"""

    peer: Optional[str] = field(
        metadata={
            'dbus_name': 'peer',
            'dbus_type': 's',
        },
        default=None,
    )
    """Specifies the name of the interface for the other side of the patch. The
    patch on the other side must also set this interface as peer."""
