# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses-jinja.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class OvsDpdkSettings(NetworkManagerSettingsMixin):
    """OvsDpdk Link Settings"""

    devargs: Optional[str] = field(
        metadata={
            'dbus_name': 'devargs',
            'dbus_type': 's',
        },
        default=None,
    )
    """Open vSwitch DPDK device arguments."""
    n_rxq: Optional[int] = field(
        metadata={
            'dbus_name': 'n-rxq',
            'dbus_type': 'u',
        },
        default=None,
    )
    """Open vSwitch DPDK number of rx queues. Defaults to zero which means to
    leave the parameter in OVS unspecified and effectively configures
    one queue."""
