# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class OvsInterfaceSettings(NetworkManagerSettingsMixin):
    """Open vSwitch Interface Settings"""

    ovs_interface_type: Optional[str] = field(
        metadata={'dbus_name': 'type', 'dbus_type': 's'},
        default=None,
    )
    """The interface type. Either "internal", "system", "patch", "dpdk", or
    empty."""
