# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class PppSettings(NetworkManagerSettingsMixin):
    """Point-to-Point Protocol Settings"""

    baud: Optional[int] = field(
        metadata={'dbus_name': 'baud', 'dbus_type': 'u'},
        default=None,
    )
    crtscts: Optional[bool] = field(
        metadata={'dbus_name': 'crtscts', 'dbus_type': 'b'},
        default=False,
    )
    lcp_echo_failure: Optional[int] = field(
        metadata={'dbus_name': 'lcp-echo-failure', 'dbus_type': 'u'},
        default=None,
    )
    lcp_echo_interval: Optional[int] = field(
        metadata={'dbus_name': 'lcp-echo-interval', 'dbus_type': 'u'},
        default=None,
    )
    mppe_stateful: Optional[bool] = field(
        metadata={'dbus_name': 'mppe-stateful', 'dbus_type': 'b'},
        default=False,
    )
    mru: Optional[int] = field(
        metadata={'dbus_name': 'mru', 'dbus_type': 'u'},
        default=None,
    )
    mtu: Optional[int] = field(
        metadata={'dbus_name': 'mtu', 'dbus_type': 'u'},
        default=None,
    )
    no_vj_comp: Optional[bool] = field(
        metadata={'dbus_name': 'no-vj-comp', 'dbus_type': 'b'},
        default=False,
    )
    noauth: Optional[bool] = field(
        metadata={'dbus_name': 'noauth', 'dbus_type': 'b'},
        default=True,
    )
    nobsdcomp: Optional[bool] = field(
        metadata={'dbus_name': 'nobsdcomp', 'dbus_type': 'b'},
        default=False,
    )
    nodeflate: Optional[bool] = field(
        metadata={'dbus_name': 'nodeflate', 'dbus_type': 'b'},
        default=False,
    )
    refuse_chap: Optional[bool] = field(
        metadata={'dbus_name': 'refuse-chap', 'dbus_type': 'b'},
        default=False,
    )
    refuse_eap: Optional[bool] = field(
        metadata={'dbus_name': 'refuse-eap', 'dbus_type': 'b'},
        default=False,
    )
    refuse_mschap: Optional[bool] = field(
        metadata={'dbus_name': 'refuse-mschap', 'dbus_type': 'b'},
        default=False,
    )
    refuse_mschapv2: Optional[bool] = field(
        metadata={'dbus_name': 'refuse-mschapv2', 'dbus_type': 'b'},
        default=False,
    )
    refuse_pap: Optional[bool] = field(
        metadata={'dbus_name': 'refuse-pap', 'dbus_type': 'b'},
        default=False,
    )
    require_mppe: Optional[bool] = field(
        metadata={'dbus_name': 'require-mppe', 'dbus_type': 'b'},
        default=False,
    )
    require_mppe_128: Optional[bool] = field(
        metadata={'dbus_name': 'require-mppe-128', 'dbus_type': 'b'},
        default=False,
    )
