# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class PppoeSettings(NetworkManagerSettingsMixin):
    """PPP-over-Ethernet Settings"""

    parent: Optional[str] = field(
        metadata={'dbus_name': 'parent', 'dbus_type': 's'},
        default=None,
    )
    password: Optional[str] = field(
        metadata={'dbus_name': 'password', 'dbus_type': 's'},
        default=None,
    )
    password_flags: Optional[int] = field(
        metadata={'dbus_name': 'password-flags', 'dbus_type': 'i'},
        default=None,
    )
    service: Optional[str] = field(
        metadata={'dbus_name': 'service', 'dbus_type': 's'},
        default=None,
    )
    username: Optional[str] = field(
        metadata={'dbus_name': 'username', 'dbus_type': 's'},
        default=None,
    )
