from __future__ import annotations

from dataclasses import dataclass, field, fields
from typing import Any, Dict, Optional

from .base import NetworkManagerSettingsMixin
from .connection import ConnectionSettings
from .ipv4 import Ipv4Settings
from .ipv6 import Ipv6Settings
from .adsl import AdslSettings
from .bluetooth import BluetoothSettings
from .bond import BondSettings
from .bond_port import BondPortSettings
from .bridge import BridgeSettings
from .bridge_port import BridgePortSettings
from .cdma import CdmaSettings
from .dcb import DcbSettings
from .ethernet import EthernetSettings
from .gsm import GsmSettings
from .hostname import HostnameSettings
from .ieee802_1x import Ieee8021XSettings
from .infiniband import InfinibandSettings
from .ip_tunnel import IpTunnelSettings
from .lowpan import LowpanSettings
from .macsec import MacsecSettings
from .macvlan import MacvlanSettings
from .match import MatchSettings
from .olpc_mesh import OlpcMeshSettings
from .ovs_bridge import OvsBridgeSettings
from .ovs_dpdk import OvsDpdkSettings
from .ovs_external_ids import OvsExternalIdsSettings
from .ovs_interface import OvsInterfaceSettings
from .ovs_patch import OvsPatchSettings
from .ovs_port import OvsPortSettings
from .ppp import PppSettings
from .pppoe import PppoeSettings
from .proxy import ProxySettings
from .serial import SerialSettings
from .team import TeamSettings
from .team_port import TeamPortSettings
from .tun import TunSettings
from .user import UserSettings
from .veth import VethSettings
from .vlan import VlanSettings
from .vpn import VpnSettings
from .vrf import VrfSettings
from .vxlan import VxlanSettings
from .wifi_p2p import WifiP2PSettings
from .wimax import WimaxSettings
from .wireguard import WireguardSettings
from .wireless import WirelessSettings
from .wireless_security import WirelessSecuritySettings
from .wpan import WpanSettings
from ..types import NetworkManagerConnectionProperties


@dataclass
class ConnectionProfile:
    """
    Connection profiles
    -------------------

    NetworkManager is based on a concept of connection profiles, most often
    referred to just as "connections". Connection profiles provide a network
    configuration. When NetworkManager activates a connection profile on a
    network device, the configuration will be applied and an active network
    connection will be established. Users are free to create as many
    connection profiles as they see fit. Thus they are flexible in having
    various network configurations for different networking needs:
    https://networkmanager.pages.freedesktop.org/NetworkManager/NetworkManager/nm-settings-dbus.html

    Connection profiles are handled by NetworkManager via a settings service
    and are exported on D-Bus (/org/freedesktop/NetworkManager/Settings/<num>)

    Definition of a connection profile:
    A specific, encapsulated, independent group of settings describing
    all the configuration required to connect to a specific network.

    It is referred to by a unique identifier called the UUID.
    A connection profile is tied to a one specific device type,
    but not necessarily a specific hardware device.

    A connection profile is composed of one or more Settings objects.

    Settings objects
    ----------------

    A group of related key/value pairs describing a specific piece
    of a Connection (profile). Keys are also referred to as properties.
    """
    # The settings object "connection" is special: It must always be present
    # because it contains the UUID and the connection type which are required:
    connection: ConnectionSettings = field(
        metadata={'dbus_name': 'connection',
                  'settings_class': ConnectionSettings},
    )
    # The list of the remaining settings classes was generated by
    # tools/generate-settings-dataclasses.py which generates the
    # settings classes themselfes as well.
    # If possible, please make changes by also updating the script.

    # start of the generated list of settings classes
    ipv4: Optional[Ipv4Settings] = field(
        metadata={'dbus_name': 'ipv4',
                  'settings_class': Ipv4Settings},
        default=None,
    )
    ipv6: Optional[Ipv6Settings] = field(
        metadata={'dbus_name': 'ipv6',
                  'settings_class': Ipv6Settings},
        default=None,
    )
    adsl: Optional[AdslSettings] = field(
        metadata={'dbus_name': 'adsl',
                  'settings_class': AdslSettings},
        default=None,
    )
    bluetooth: Optional[BluetoothSettings] = field(
        metadata={'dbus_name': 'bluetooth',
                  'settings_class': BluetoothSettings},
        default=None,
    )
    bond: Optional[BondSettings] = field(
        metadata={'dbus_name': 'bond',
                  'settings_class': BondSettings},
        default=None,
    )
    bond_port: Optional[BondPortSettings] = field(
        metadata={'dbus_name': 'bond-port',
                  'settings_class': BondPortSettings},
        default=None,
    )
    bridge: Optional[BridgeSettings] = field(
        metadata={'dbus_name': 'bridge',
                  'settings_class': BridgeSettings},
        default=None,
    )
    bridge_port: Optional[BridgePortSettings] = field(
        metadata={'dbus_name': 'bridge-port',
                  'settings_class': BridgePortSettings},
        default=None,
    )
    cdma: Optional[CdmaSettings] = field(
        metadata={'dbus_name': 'cdma',
                  'settings_class': CdmaSettings},
        default=None,
    )
    dcb: Optional[DcbSettings] = field(
        metadata={'dbus_name': 'dcb',
                  'settings_class': DcbSettings},
        default=None,
    )
    ethernet: Optional[EthernetSettings] = field(
        metadata={'dbus_name': '802-3-ethernet',
                  'settings_class': EthernetSettings},
        default=None,
    )
    gsm: Optional[GsmSettings] = field(
        metadata={'dbus_name': 'gsm',
                  'settings_class': GsmSettings},
        default=None,
    )
    hostname: Optional[HostnameSettings] = field(
        metadata={'dbus_name': 'hostname',
                  'settings_class': HostnameSettings},
        default=None,
    )
    ieee802_1x: Optional[Ieee8021XSettings] = field(
        metadata={'dbus_name': '802-1x',
                  'settings_class': Ieee8021XSettings},
        default=None,
    )
    infiniband: Optional[InfinibandSettings] = field(
        metadata={'dbus_name': 'infiniband',
                  'settings_class': InfinibandSettings},
        default=None,
    )
    ip_tunnel: Optional[IpTunnelSettings] = field(
        metadata={'dbus_name': 'ip-tunnel',
                  'settings_class': IpTunnelSettings},
        default=None,
    )
    lowpan: Optional[LowpanSettings] = field(
        metadata={'dbus_name': '6lowpan',
                  'settings_class': LowpanSettings},
        default=None,
    )
    macsec: Optional[MacsecSettings] = field(
        metadata={'dbus_name': 'macsec',
                  'settings_class': MacsecSettings},
        default=None,
    )
    macvlan: Optional[MacvlanSettings] = field(
        metadata={'dbus_name': 'macvlan',
                  'settings_class': MacvlanSettings},
        default=None,
    )
    match: Optional[MatchSettings] = field(
        metadata={'dbus_name': 'match',
                  'settings_class': MatchSettings},
        default=None,
    )
    olpc_mesh: Optional[OlpcMeshSettings] = field(
        metadata={'dbus_name': '802-11-olpc-mesh',
                  'settings_class': OlpcMeshSettings},
        default=None,
    )
    ovs_bridge: Optional[OvsBridgeSettings] = field(
        metadata={'dbus_name': 'ovs-bridge',
                  'settings_class': OvsBridgeSettings},
        default=None,
    )
    ovs_dpdk: Optional[OvsDpdkSettings] = field(
        metadata={'dbus_name': 'ovs-dpdk',
                  'settings_class': OvsDpdkSettings},
        default=None,
    )
    ovs_external_ids: Optional[OvsExternalIdsSettings] = field(
        metadata={'dbus_name': 'ovs-external-ids',
                  'settings_class': OvsExternalIdsSettings},
        default=None,
    )
    ovs_interface: Optional[OvsInterfaceSettings] = field(
        metadata={'dbus_name': 'ovs-interface',
                  'settings_class': OvsInterfaceSettings},
        default=None,
    )
    ovs_patch: Optional[OvsPatchSettings] = field(
        metadata={'dbus_name': 'ovs-patch',
                  'settings_class': OvsPatchSettings},
        default=None,
    )
    ovs_port: Optional[OvsPortSettings] = field(
        metadata={'dbus_name': 'ovs-port',
                  'settings_class': OvsPortSettings},
        default=None,
    )
    ppp: Optional[PppSettings] = field(
        metadata={'dbus_name': 'ppp',
                  'settings_class': PppSettings},
        default=None,
    )
    pppoe: Optional[PppoeSettings] = field(
        metadata={'dbus_name': 'pppoe',
                  'settings_class': PppoeSettings},
        default=None,
    )
    proxy: Optional[ProxySettings] = field(
        metadata={'dbus_name': 'proxy',
                  'settings_class': ProxySettings},
        default=None,
    )
    serial: Optional[SerialSettings] = field(
        metadata={'dbus_name': 'serial',
                  'settings_class': SerialSettings},
        default=None,
    )
    team: Optional[TeamSettings] = field(
        metadata={'dbus_name': 'team',
                  'settings_class': TeamSettings},
        default=None,
    )
    team_port: Optional[TeamPortSettings] = field(
        metadata={'dbus_name': 'team-port',
                  'settings_class': TeamPortSettings},
        default=None,
    )
    tun: Optional[TunSettings] = field(
        metadata={'dbus_name': 'tun',
                  'settings_class': TunSettings},
        default=None,
    )
    user: Optional[UserSettings] = field(
        metadata={'dbus_name': 'user',
                  'settings_class': UserSettings},
        default=None,
    )
    veth: Optional[VethSettings] = field(
        metadata={'dbus_name': 'veth',
                  'settings_class': VethSettings},
        default=None,
    )
    vlan: Optional[VlanSettings] = field(
        metadata={'dbus_name': 'vlan',
                  'settings_class': VlanSettings},
        default=None,
    )
    vpn: Optional[VpnSettings] = field(
        metadata={'dbus_name': 'vpn',
                  'settings_class': VpnSettings},
        default=None,
    )
    vrf: Optional[VrfSettings] = field(
        metadata={'dbus_name': 'vrf',
                  'settings_class': VrfSettings},
        default=None,
    )
    vxlan: Optional[VxlanSettings] = field(
        metadata={'dbus_name': 'vxlan',
                  'settings_class': VxlanSettings},
        default=None,
    )
    wifi_p2p: Optional[WifiP2PSettings] = field(
        metadata={'dbus_name': 'wifi-p2p',
                  'settings_class': WifiP2PSettings},
        default=None,
    )
    wimax: Optional[WimaxSettings] = field(
        metadata={'dbus_name': 'wimax',
                  'settings_class': WimaxSettings},
        default=None,
    )
    wireguard: Optional[WireguardSettings] = field(
        metadata={'dbus_name': 'wireguard',
                  'settings_class': WireguardSettings},
        default=None,
    )
    wireless: Optional[WirelessSettings] = field(
        metadata={'dbus_name': '802-11-wireless',
                  'settings_class': WirelessSettings},
        default=None,
    )
    wireless_security: Optional[WirelessSecuritySettings] = field(
        metadata={'dbus_name': '802-11-wireless-security',
                  'settings_class': WirelessSecuritySettings},
        default=None,
    )
    wpan: Optional[WpanSettings] = field(
        metadata={'dbus_name': 'wpan',
                  'settings_class': WpanSettings},
        default=None,
    )
    # end of the generated list of settings classes

    def to_dbus(self) -> NetworkManagerConnectionProperties:
        new_dict: NetworkManagerConnectionProperties = {}

        for x in fields(self):
            value = getattr(self, x.name)
            if value is None:
                continue

            new_dict[x.metadata['dbus_name']] = value.to_dbus()

        return new_dict

    @property
    def dbus_name_to_settings_class(self) -> Dict[str, str]:
        return {f.metadata['dbus_name']: f.name
                for f in fields(self)}

    @classmethod
    def from_dbus(cls, dbus_dict: NetworkManagerConnectionProperties
                  ) -> ConnectionProfile:
        for domain in ("ipv4", "ipv6"):
            group = dbus_dict.get(domain, None)
            if group:
                for key in ("addresses", "routes"):
                    group.pop(key, None)
        try:
            unvarianted_options: Dict[str, Any] = {
                SETTING_DBUS_NAME_TO_NAME[k]: SETTING_TO_CLASS[k].from_dbus(v)
                for k, v in dbus_dict.items()}
        except KeyError as e:
            print(dbus_dict)
            raise e
        return cls(**unvarianted_options)


SETTING_DBUS_NAME_TO_NAME: Dict[str, str] = {
    f.metadata['dbus_name']: f.name
    for f in fields(ConnectionProfile)
}

SETTING_TO_CLASS: Dict[str, NetworkManagerSettingsMixin] = {
    f.metadata['dbus_name']: f.metadata['settings_class']
    for f in fields(ConnectionProfile)
}
