# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class SerialSettings(NetworkManagerSettingsMixin):
    """Serial Link Settings"""

    baud: Optional[int] = field(
        metadata={'dbus_name': 'baud', 'dbus_type': 'u'},
        default=57600,
    )
    bits: Optional[int] = field(
        metadata={'dbus_name': 'bits', 'dbus_type': 'u'},
        default=8,
    )
    parity: Optional[int] = field(
        metadata={'dbus_name': 'parity', 'dbus_type': 'y'},
        default=None,
    )
    send_delay: Optional[int] = field(
        metadata={'dbus_name': 'send-delay', 'dbus_type': 't'},
        default=None,
    )
    stopbits: Optional[int] = field(
        metadata={'dbus_name': 'stopbits', 'dbus_type': 'u'},
        default=1,
    )
