# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Optional
from .base import NetworkManagerSettingsMixin
from .datatypes import LinkWatchers


@dataclass
class TeamPortSettings(NetworkManagerSettingsMixin):
    """Team Port Settings"""

    config: Optional[str] = field(
        metadata={'dbus_name': 'config', 'dbus_type': 's'},
        default=None,
    )
    """The JSON configuration for the team port. The property should contain raw
    JSON configuration data suitable for teamd, because the value is passed
    directly to teamd. If not specified, the default configuration is used. See
    man teamd.conf for the format details."""
    lacp_key: Optional[int] = field(
        metadata={'dbus_name': 'lacp-key', 'dbus_type': 'i'},
        default=None,
    )
    lacp_prio: Optional[int] = field(
        metadata={'dbus_name': 'lacp-prio', 'dbus_type': 'i'},
        default=None,
    )
    link_watchers: Optional[List[LinkWatchers]] = field(
        metadata={'dbus_name': 'link-watchers',
                  'dbus_type': 'aa{sv}',
                  'dbus_inner_class': LinkWatchers},
        default=None,
    )
    prio: Optional[int] = field(
        metadata={'dbus_name': 'prio', 'dbus_type': 'i'},
        default=None,
    )
    queue_id: Optional[int] = field(
        metadata={'dbus_name': 'queue-id', 'dbus_type': 'i'},
        default=None,
    )
    """Corresponds to the teamd ports.PORTIFNAME.queue_id. When set to -1 means
    the parameter is skipped from the json config."""
    sticky: Optional[bool] = field(
        metadata={'dbus_name': 'sticky', 'dbus_type': 'b'},
        default=False,
    )
