# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Optional
from .base import NetworkManagerSettingsMixin
from .datatypes import LinkWatchers


@dataclass
class TeamPortSettings(NetworkManagerSettingsMixin):
    """Team Port Settings"""

    config: Optional[str] = field(
        metadata={'dbus_name': 'config', 'dbus_type': 's'},
        default=None,
    )
    lacp_key: Optional[int] = field(
        metadata={'dbus_name': 'lacp-key', 'dbus_type': 'i'},
        default=None,
    )
    lacp_prio: Optional[int] = field(
        metadata={'dbus_name': 'lacp-prio', 'dbus_type': 'i'},
        default=None,
    )
    link_watchers: Optional[List[LinkWatchers]] = field(
        metadata={'dbus_name': 'link-watchers',
                  'dbus_type': 'aa{sv}',
                  'dbus_inner_class': LinkWatchers},
        default=None,
    )
    prio: Optional[int] = field(
        metadata={'dbus_name': 'prio', 'dbus_type': 'i'},
        default=None,
    )
    queue_id: Optional[int] = field(
        metadata={'dbus_name': 'queue-id', 'dbus_type': 'i'},
        default=None,
    )
    sticky: Optional[bool] = field(
        metadata={'dbus_name': 'sticky', 'dbus_type': 'b'},
        default=False,
    )
