# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class TunSettings(NetworkManagerSettingsMixin):
    """Tunnel Settings"""

    group: Optional[str] = field(
        metadata={'dbus_name': 'group', 'dbus_type': 's'},
        default=None,
    )
    mode: Optional[int] = field(
        metadata={'dbus_name': 'mode', 'dbus_type': 'u'},
        default=1,
    )
    multi_queue: Optional[bool] = field(
        metadata={'dbus_name': 'multi-queue', 'dbus_type': 'b'},
        default=False,
    )
    owner: Optional[str] = field(
        metadata={'dbus_name': 'owner', 'dbus_type': 's'},
        default=None,
    )
    pi: Optional[bool] = field(
        metadata={'dbus_name': 'pi', 'dbus_type': 'b'},
        default=False,
    )
    vnet_hdr: Optional[bool] = field(
        metadata={'dbus_name': 'vnet-hdr', 'dbus_type': 'b'},
        default=False,
    )
