# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses-jinja.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class UserSettings(NetworkManagerSettingsMixin):
    """General User Profile Settings"""

    data: Optional[Dict[str, str]] = field(
        metadata={
            'dbus_name': 'data',
            'dbus_type': 'a{ss}',
        },
        default=None,
    )
    """A dictionary of key/value pairs with user data. This data is ignored by
    NetworkManager and can be used at the users discretion. The keys
    only support a strict ascii format, but the values can be arbitrary
    UTF8 strings up to a certain length."""
