# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses-jinja.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class VethSettings(NetworkManagerSettingsMixin):
    """Veth Settings"""

    peer: Optional[str] = field(
        metadata={
            'dbus_name': 'peer',
            'dbus_type': 's',
        },
        default=None,
    )
    """This property specifies the peer interface name of the veth. This
    property is mandatory."""
