# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class VlanSettings(NetworkManagerSettingsMixin):
    """VLAN Settings"""

    egress_priority_map: Optional[List[str]] = field(
        metadata={'dbus_name': 'egress-priority-map', 'dbus_type': 'as'},
        default=None,
    )
    flags: Optional[int] = field(
        metadata={'dbus_name': 'flags', 'dbus_type': 'i'},
        default=None,
    )
    vlan_id: Optional[int] = field(
        metadata={'dbus_name': 'id', 'dbus_type': 'u'},
        default=None,
    )
    ingress_priority_map: Optional[List[str]] = field(
        metadata={'dbus_name': 'ingress-priority-map', 'dbus_type': 'as'},
        default=None,
    )
    interface_name: Optional[str] = field(
        metadata={'dbus_name': 'interface-name', 'dbus_type': 's'},
        default=None,
    )
    parent: Optional[str] = field(
        metadata={'dbus_name': 'parent', 'dbus_type': 's'},
        default=None,
    )
