# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List, Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class VpnSettings(NetworkManagerSettingsMixin):
    """VPN Settings"""

    data: Optional[Dict[str, str]] = field(
        metadata={'dbus_name': 'data', 'dbus_type': 'a{ss}'},
        default=None,
    )
    persistent: Optional[bool] = field(
        metadata={'dbus_name': 'persistent', 'dbus_type': 'b'},
        default=False,
    )
    secrets: Optional[Dict[str, str]] = field(
        metadata={'dbus_name': 'secrets', 'dbus_type': 'a{ss}'},
        default=None,
    )
    service_type: Optional[str] = field(
        metadata={'dbus_name': 'service-type', 'dbus_type': 's'},
        default=None,
    )
    timeout: Optional[int] = field(
        metadata={'dbus_name': 'timeout', 'dbus_type': 'u'},
        default=None,
    )
    user_name: Optional[str] = field(
        metadata={'dbus_name': 'user-name', 'dbus_type': 's'},
        default=None,
    )
