# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class VrfSettings(NetworkManagerSettingsMixin):
    """VRF settings"""

    table: Optional[int] = field(
        metadata={'dbus_name': 'table', 'dbus_type': 'u'},
        default=None,
    )
