# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class VxlanSettings(NetworkManagerSettingsMixin):
    """VXLAN Settings"""

    ageing: Optional[int] = field(
        metadata={'dbus_name': 'ageing', 'dbus_type': 'u'},
        default=300,
    )
    destination_port: Optional[int] = field(
        metadata={'dbus_name': 'destination-port', 'dbus_type': 'u'},
        default=8472,
    )
    vxlan_id: Optional[int] = field(
        metadata={'dbus_name': 'id', 'dbus_type': 'u'},
        default=None,
    )
    l2_miss: Optional[bool] = field(
        metadata={'dbus_name': 'l2-miss', 'dbus_type': 'b'},
        default=False,
    )
    l3_miss: Optional[bool] = field(
        metadata={'dbus_name': 'l3-miss', 'dbus_type': 'b'},
        default=False,
    )
    learning: Optional[bool] = field(
        metadata={'dbus_name': 'learning', 'dbus_type': 'b'},
        default=True,
    )
    limit: Optional[int] = field(
        metadata={'dbus_name': 'limit', 'dbus_type': 'u'},
        default=None,
    )
    local: Optional[str] = field(
        metadata={'dbus_name': 'local', 'dbus_type': 's'},
        default=None,
    )
    parent: Optional[str] = field(
        metadata={'dbus_name': 'parent', 'dbus_type': 's'},
        default=None,
    )
    proxy: Optional[bool] = field(
        metadata={'dbus_name': 'proxy', 'dbus_type': 'b'},
        default=False,
    )
    remote: Optional[str] = field(
        metadata={'dbus_name': 'remote', 'dbus_type': 's'},
        default=None,
    )
    rsc: Optional[bool] = field(
        metadata={'dbus_name': 'rsc', 'dbus_type': 'b'},
        default=False,
    )
    source_port_max: Optional[int] = field(
        metadata={'dbus_name': 'source-port-max', 'dbus_type': 'u'},
        default=None,
    )
    source_port_min: Optional[int] = field(
        metadata={'dbus_name': 'source-port-min', 'dbus_type': 'u'},
        default=None,
    )
    tos: Optional[int] = field(
        metadata={'dbus_name': 'tos', 'dbus_type': 'u'},
        default=None,
    )
    ttl: Optional[int] = field(
        metadata={'dbus_name': 'ttl', 'dbus_type': 'u'},
        default=None,
    )
