# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class WifiP2PSettings(NetworkManagerSettingsMixin):
    """Wi-Fi P2P Settings"""

    peer: Optional[str] = field(
        metadata={'dbus_name': 'peer', 'dbus_type': 's'},
        default=None,
    )
    wfd_ies: Optional[bytes] = field(
        metadata={'dbus_name': 'wfd-ies', 'dbus_type': 'ay'},
        default=None,
    )
    wps_method: Optional[int] = field(
        metadata={'dbus_name': 'wps-method', 'dbus_type': 'u'},
        default=None,
    )
