# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class WirelessSettings(NetworkManagerSettingsMixin):
    """Wi-Fi Settings"""

    ap_isolation: Optional[int] = field(
        metadata={'dbus_name': 'ap-isolation', 'dbus_type': 'i'},
        default=None,
    )
    assigned_mac_address: Optional[str] = field(
        metadata={'dbus_name': 'assigned-mac-address', 'dbus_type': 's'},
        default=None,
    )
    band: Optional[str] = field(
        metadata={'dbus_name': 'band', 'dbus_type': 's'},
        default=None,
    )
    bssid: Optional[bytes] = field(
        metadata={'dbus_name': 'bssid', 'dbus_type': 'ay'},
        default=None,
    )
    channel: Optional[int] = field(
        metadata={'dbus_name': 'channel', 'dbus_type': 'u'},
        default=None,
    )
    cloned_mac_address: Optional[bytes] = field(
        metadata={'dbus_name': 'cloned-mac-address', 'dbus_type': 'ay'},
        default=None,
    )
    generate_mac_address_mask: Optional[str] = field(
        metadata={'dbus_name': 'generate-mac-address-mask', 'dbus_type': 's'},
        default=None,
    )
    hidden: Optional[bool] = field(
        metadata={'dbus_name': 'hidden', 'dbus_type': 'b'},
        default=False,
    )
    mac_address: Optional[bytes] = field(
        metadata={'dbus_name': 'mac-address', 'dbus_type': 'ay'},
        default=None,
    )
    mac_address_blacklist: Optional[List[str]] = field(
        metadata={'dbus_name': 'mac-address-blacklist', 'dbus_type': 'as'},
        default=None,
    )
    mac_address_randomization: Optional[int] = field(
        metadata={'dbus_name': 'mac-address-randomization', 'dbus_type': 'u'},
        default=None,
    )
    mode: Optional[str] = field(
        metadata={'dbus_name': 'mode', 'dbus_type': 's'},
        default=None,
    )
    mtu: Optional[int] = field(
        metadata={'dbus_name': 'mtu', 'dbus_type': 'u'},
        default=None,
    )
    powersave: Optional[int] = field(
        metadata={'dbus_name': 'powersave', 'dbus_type': 'u'},
        default=None,
    )
    rate: Optional[int] = field(
        metadata={'dbus_name': 'rate', 'dbus_type': 'u'},
        default=None,
    )
    security: Optional[str] = field(
        metadata={'dbus_name': 'security', 'dbus_type': 's'},
        default=None,
    )
    seen_bssids: Optional[List[str]] = field(
        metadata={'dbus_name': 'seen-bssids', 'dbus_type': 'as'},
        default=None,
    )
    ssid: Optional[bytes] = field(
        metadata={'dbus_name': 'ssid', 'dbus_type': 'ay'},
        default=None,
    )
    tx_power: Optional[int] = field(
        metadata={'dbus_name': 'tx-power', 'dbus_type': 'u'},
        default=None,
    )
    wake_on_wlan: Optional[int] = field(
        metadata={'dbus_name': 'wake-on-wlan', 'dbus_type': 'u'},
        default=1,
    )
