# SPDX-License-Identifier: LGPL-2.1-or-later
# This file was generated by tools/generate-settings-dataclasses.py,
# if possible, please make changes by also updating the script.
from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Optional
from .base import NetworkManagerSettingsMixin


@dataclass
class WirelessSecuritySettings(NetworkManagerSettingsMixin):
    """Wi-Fi Security Settings"""

    auth_alg: Optional[str] = field(
        metadata={'dbus_name': 'auth-alg', 'dbus_type': 's'},
        default=None,
    )
    fils: Optional[int] = field(
        metadata={'dbus_name': 'fils', 'dbus_type': 'i'},
        default=None,
    )
    group: Optional[List[str]] = field(
        metadata={'dbus_name': 'group', 'dbus_type': 'as'},
        default=None,
    )
    key_mgmt: Optional[str] = field(
        metadata={'dbus_name': 'key-mgmt', 'dbus_type': 's'},
        default=None,
    )
    leap_password: Optional[str] = field(
        metadata={'dbus_name': 'leap-password', 'dbus_type': 's'},
        default=None,
    )
    leap_password_flags: Optional[int] = field(
        metadata={'dbus_name': 'leap-password-flags', 'dbus_type': 'i'},
        default=None,
    )
    leap_username: Optional[str] = field(
        metadata={'dbus_name': 'leap-username', 'dbus_type': 's'},
        default=None,
    )
    pairwise: Optional[List[str]] = field(
        metadata={'dbus_name': 'pairwise', 'dbus_type': 'as'},
        default=None,
    )
    pmf: Optional[int] = field(
        metadata={'dbus_name': 'pmf', 'dbus_type': 'i'},
        default=None,
    )
    proto: Optional[List[str]] = field(
        metadata={'dbus_name': 'proto', 'dbus_type': 'as'},
        default=None,
    )
    psk: Optional[str] = field(
        metadata={'dbus_name': 'psk', 'dbus_type': 's'},
        default=None,
    )
    psk_flags: Optional[int] = field(
        metadata={'dbus_name': 'psk-flags', 'dbus_type': 'i'},
        default=None,
    )
    wep_key_flags: Optional[int] = field(
        metadata={'dbus_name': 'wep-key-flags', 'dbus_type': 'i'},
        default=None,
    )
    wep_key_type: Optional[int] = field(
        metadata={'dbus_name': 'wep-key-type', 'dbus_type': 'i'},
        default=None,
    )
    wep_key0: Optional[str] = field(
        metadata={'dbus_name': 'wep-key0', 'dbus_type': 's'},
        default=None,
    )
    wep_key1: Optional[str] = field(
        metadata={'dbus_name': 'wep-key1', 'dbus_type': 's'},
        default=None,
    )
    wep_key2: Optional[str] = field(
        metadata={'dbus_name': 'wep-key2', 'dbus_type': 's'},
        default=None,
    )
    wep_key3: Optional[str] = field(
        metadata={'dbus_name': 'wep-key3', 'dbus_type': 's'},
        default=None,
    )
    wep_tx_keyidx: Optional[int] = field(
        metadata={'dbus_name': 'wep-tx-keyidx', 'dbus_type': 'u'},
        default=None,
    )
    wps_method: Optional[int] = field(
        metadata={'dbus_name': 'wps-method', 'dbus_type': 'u'},
        default=None,
    )
